### ISSUE TITLE
Testing major version changes against Terrainbento?

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#1278]
Terrainbento's test suite represents an addition set of tests of Landlab. Many of the tests are based on analytical solutions, and sometimes changes in Landlab can unexpectedly break terrainbento. 

For example, many tests started to fail in Terrainbento after #1210 (see #1276, #1277 , and TerrainBento/terrainbento/issues/156)

I'd like to start a discussion about whether it is worth testing against terrainbento for landlab releases. The main reason not to test is that the tests take a while. The main reason to test is that terrainbento has a ton of example use cases, that include tests of Landlab's behavior that extend beyond what is in the standard test suite. 

@mcflugen @gregtucker

**Comment by gregtucker** [comment]
I think it would be a good idea, for releases (not for every Landlab PR). Ideally, anyone who modifies any of the components that TB actually uses would also test against TB. At the moment, the group of people who are likely to do this is probably small enough that we could simply send word to this group that it's a good idea to run the TB tests before merging.

**Comment by kbarnhart** [comment]
@gregtucker agreed that this should only be for releases. @mcflugen and I discussed this briefly the other day when he gave me pointers about updating the terrainbento CI.  In progress at TerrainBento/terrainbento/pull/158.

In theory once I have working github actions for the terrainbento CI this should be pretty simple to implement. 

In reflecting on this a bit more, I think the other reason to do this is that terrainbento probably represents the most extensive collection of tests that landlab components interacting.

Going to leave this open if others feel compelled to discuss.

**Comment by mcflugen** [comment]
I think this makes a lot of sense. We should probably test as many of landlab's [dependent packages](https://github.com/landlab/landlab/network/dependents) as possible. Some others could include:
* DepuitLEM
* Compaction
* Umami
* Sequence
* Plume

I think all of those come with test suites.

We could then have a separate GitHub actions file for each of these that runs on a version tag. A question then would be what version of the dependent package do we test with? The latest development version? The latest release? I think we would probably want to test the latest release, in which case the test would have to checkout the latest version of the dependent package and then run its tests.

Using *terrainbento* as an example, maybe the workflow file could look something like the following?
```yaml
# test-terrainbento.yml
name: Test TerrainBento

on: [push, pull_request]
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Checkout dependent
        uses: actions/checkout@v2
        with:
          repository: 'TerrainBento/terrainbento'
          ref: 'v2.0.0'
          path: 'terrainbento'

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: true

      - name: Show conda installation info
        run: |
          conda info
          conda list

      - name: Install landlab requirements
        run: |
          conda install mamba
          mamba install --file=requirements.txt
          mamba list

      - name: Build and install landlab
        run: |
          pip install -e .

      - name: Install testing dependencies
        run: mamba install --file=requirements-testing.txt

      - name: Install and test dependent
        run: |
          cd terrainbento
          pip install -e .
          pytest .
```
