### ISSUE TITLE
Changing the way black works...?

### ISSUE THREAD

**Issue by SiccarPoint** [landlab/landlab#1324]
Hi all,

Having spent some recent time developing again, I've found some of the CI changes pretty hostile. In particular, `black` is _really_ frustrating to have to implement at the user end. It produces fairly hard-to-read errors, and no guidance on how to fix these anything other than manually. Waiting several minutes for tests to initiate, expecting to wait ~20, only to find they crashed out within 60 seconds because of a completely trivial formatting failure is also really annoying.

My feeling is that if we want to enforce black's really tight formatting rules (which I guess is not unreasonable), then this shouldn't be the responsibility of the creator of the PR. It should be applied during the merge in an automated fashion. After all, the code is either not black compliant, in which case the PR is not permitted, or the user makes the changes exactly as black demands, and then it is. There is no element of user choice here, so making them do it themselves isn't necessary. If the black formatting looks stupid or does something that isn't sensible... doesn't matter, still has to be black-compliant for tests to pass, there's no way around it.

Failing that - which I still think is the best decision - at the very least, a black failure should be accompanied by text output to tell the user that they should now run black locally to fix the problems (i.e., `black .` from the landlab dir). I can imagine some poor future developer trawling back through their code in a big PR trying to fix all their fails by hand, missing some, getting more CI fails, doing it again, etc, without realising there's a much simpler way.

**Comment by kbarnhart** [comment]
@SiccarPoint I'm glad you brought this up. 

One thing I thought a bit about while doing some pre-2.0 work was how we would enforce these standards, and how long we'd be able to manage it...

I know many people who use pre-commit black hooks to do enforce that they always run black and a linter and can't commit unless they pass... but that then requires people configure those capabilities... which isn't terribly hard, but is yet another thing.

My two cents is that in the hierarchy, we should care way more about lint than about black. Black is easy to run and there are no decisions a developer needs to make. Lint, on the other hand is an accumulation of development decisions... 

Am curious about @mcflugen's thoughts here.

**Comment by kbarnhart** [comment]
Also perhaps updating the pages describing style enforcement 

https://landlab.readthedocs.io/en/master/development/practices/style_conventions.html

But I like your point @SiccarPoint about printing a useful error message.

**Comment by mcflugen** [comment]
@SiccarPoint @kbarnhart How about setting up a pre-commit hook? It's something I've done with other projects and seems to work pretty well. Once set up, every time you make a commit, your pre-commit hooks—which could include *black* or *flake8*—will run. If you have *black* set up to run and there is a problem with a file, *black* will automatically be run on the non-conforming file and fix it.

To set this up, you have to first install *pre-commit*,
```bash
$ conda install pre-commit
```
Create a *pre-commit* config file, *.pre-commit-config.yaml*. Here is the contents of one I use that runs *black* and *flake8*,
```yaml
# .pre-commit-config.yaml
repos:
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black
    name: black
    description: "Black: The uncompromising Python code formatter"
    entry: black
    language: python
    language_version: python3
    minimum_pre_commit_version: 2.9.2
    require_serial: true
    types_or: [python, pyi]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear]
```
Install the hooks,
```bash
$ pre-commit install
```

If you think this might be a good solution, we can add this config file to *landlab* so that new users wouldn't have to create it themselves (they would still have to run `pre-commit install`).

My workflow has been to just run *black* before every push, which is easy enough to do—so long as you know to do it!

Something else we could do is to create a pull request template the explains our coding style as described by the link @kbarnhart referenced.

Although not ideal, I think we should at least implement these two changes—adding a *pre-commit* config file, and creating a pull request template—but I recognize those may not be sufficient.
