### ISSUE TITLE
Magical Constructor

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#865]
@mcflugen and I discussed revamping the current `create_and_initialize` function for model grids. 

This is motivated by wanting to make terrainbento fully pyMT compatible.

The vision is to make it possible (easy, clean, and extensible) to create a model grid, create fields, and set boundary conditions from a dictionary (and/or yaml file). 

To support this, I've updated the origin methods (PR #833), created synthetic fields (#827), improved the basic `from_file` and `from_dict` constructors (PR #826). 

The idea would be that a yaml file that looks something like below could be used to create a model grid. 

```yaml
# section 1: describe the type of grid desired:
grid:
  RasterModelGrid: 
    shape : (nrows, cols)
    xy_spacing : (3, 5)
    xy_of_lower_left : (10.0, 1.0)
    # any other kwargs to the RasterModelGrid __init__ method could be passed here

# section 2 create fields     
fields:
  at_node: # first we specify where the fields go.
    topographic__elevation: # then we specify the name of the field
      read_esrii_ascii: # we can chain together any number of functions.
        asc_file: 'input_name.txt'
        halo: 1
        no_data_value: -9999
      random: 
        distribution: 'normal'
      # so this example read the values from input_name.txt and then added
      # standard mean zero, std one normally distributed noise. 
    soil__depth:
      plane:
        point: (0., 0., 0.)
        normal: (-1, -1, 1)
      random: 
        distribution: 'uniform'
        low: 1
        high: 4
  at_link:
    name_of_field_at_link:
      # any number of fields could be initialized, either from file or synthetically.
 
# section 3 set boundary conditions        
# this section contains a list, indicating that the 
# functions would be called in a particular order 
boundary_conditions: 
    - set_watershed_boundary_condition:
        node_data: 'topographic__elevation'
```

The idea would be that the `create_and_initialize` method would support what functionality currently exists in landlab, and could be extended as needed.

Tagging all in case you want to comment. I'm going to start on a PR that implements this as I expect it will help clarify what this should look like. 

@gregtucker @mcflugen @nicgaspar @erkanistan @SiccarPoint @nathanlyons @margauxmouchene @saisiddu
